//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malden.Portal.Data.TableStorage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UseDevelopmentStorage=true")]
        public string DebugConnectionString {
            get {
                return ((string)(this["DebugConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=maldendemo;AccountKey=tG5mp8Rd5017eB4l" +
            "oqRCLQzCWQ54OKJCl3QSGvjZz2gp6ycDi2zwvBnrCqehRZhnJOQuA49O5QA0UkJaXfW6Ug==")]
        public string PrivatePortalConnectionString {
            get {
                return ((string)(this["PrivatePortalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=swmel;AccountKey=adea5aZ1m4li87GSfGEgP" +
            "F6qFmZRCrRUSC3mSAuab4sULa93rIHzle4WLRDDJPa+DFtG4+if+fAOZPdyXiNWVQ==")]
        public string LiveConnectionString {
            get {
                return ((string)(this["LiveConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1051200")]
        public string BlobCacheControlValue {
            get {
                return ((string)(this["BlobCacheControlValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("swmel")]
        public string LiveDbName {
            get {
                return ((string)(this["LiveDbName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://az649978.vo.msecnd.net")]
        public string PrivatePortalCDNEndPoint {
            get {
                return ((string)(this["PrivatePortalCDNEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://upgrades.malden.co.uk")]
        public string LiveCDNEndPoint {
            get {
                return ((string)(this["LiveCDNEndPoint"]));
            }
        }
    }
}
